version: 2

ref:
  workspace_directory: &workspace_directory
    ~/workspace/code

  node_container: &node_container
    docker:
      - image: circleci/node:10.13.0-stretch
    workinig_directory: *workspace_directory  

jobs:
  build:
    <<: *node_container
    steps:
      - checkout
      - run:
          name: Install Dependency
          command: yarn install
      - run:
          name: Build
          command: yarn build

  test:
    <<: *node_container
    steps:
      - run:
        name: Test
        command: yarn test:unit