version: 2

jobs:
  build:
    docker: &docker_image
      - image: circleci/node:10.13.0-stretch
    workinig_directory: &workinig_directory ~/workspace/code
    steps:
      - checkout
      - run:
          name: Install Dependency
          command: yarn install
      - run:
          name: Build
          command: yarn build

  test:
    docker:
      <<: *docker_image
    working_directory: *working_directory
    steps:
      - run:
        name: Test
        command: yarn test:unit