version: 2

ref:
  workspace_directory: &workspace_directory
    ~/workspace/code

  node_container: &node_container
    docker:
      - image: circleci/node:10.13.0-stretch
    workinig_directory: *workspace_directory  

jobs:
  build:
    <<: *node_container
    steps:
      - checkout
      - run:
          name: Install Dependency
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
        root: ~/workspace
        paths:
          - code

  test:
    <<: *node_container
    steps:
      - attach_workspace:
        at: ~/workspace
      - run:
        name: Unit Test
        command: yarn test:unit

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test: 
        requires:
          - build